# Generated by Django 2.0.7 on 2020-11-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201117_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
